<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-16">
<meta name="description" content="Confirmatory protocol for P01 on an independent sample. Feasibility probes computed; two validation gates need human labels; awaiting peer review.">

<title>Advocacy and practice in meta-research: protocol – Automated meta-research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1861f82967d66f654154b492be169a53.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-d72254f1cca27c889edf43d9473ffb8d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-1861f82967d66f654154b492be169a53.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Automated meta-research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../agenda.html"> 
<span class="menu-text">Agenda</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../results.html"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../reviews.html"> 
<span class="menu-text">Reviews</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../landscape.html"> 
<span class="menu-text">Landscape</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../corpus.html"> 
<span class="menu-text">Corpus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../methods.html"> 
<span class="menu-text">How this was done</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/choxos/autometaresearch"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-this-design-exists" id="toc-why-this-design-exists" class="nav-link active" data-scroll-target="#why-this-design-exists">1. Why this design exists</a></li>
  <li><a href="#objective-and-hypothesis" id="toc-objective-and-hypothesis" class="nav-link" data-scroll-target="#objective-and-hypothesis">2. Objective and hypothesis</a></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design">3. Design</a></li>
  <li><a href="#sample" id="toc-sample" class="nav-link" data-scroll-target="#sample">4. Sample</a>
  <ul class="collapse">
  <li><a href="#frame" id="toc-frame" class="nav-link" data-scroll-target="#frame">4.1 Frame</a></li>
  <li><a href="#eligibility" id="toc-eligibility" class="nav-link" data-scroll-target="#eligibility">4.2 Eligibility</a></li>
  <li><a href="#screening" id="toc-screening" class="nav-link" data-scroll-target="#screening">4.3 Screening</a></li>
  </ul></li>
  <li><a href="#exposure" id="toc-exposure" class="nav-link" data-scroll-target="#exposure">5. Exposure</a></li>
  <li><a href="#outcome" id="toc-outcome" class="nav-link" data-scroll-target="#outcome">6. Outcome</a>
  <ul class="collapse">
  <li><a href="#extraction" id="toc-extraction" class="nav-link" data-scroll-target="#extraction">6.1 Extraction</a></li>
  <li><a href="#grading" id="toc-grading" class="nav-link" data-scroll-target="#grading">6.2 Grading</a></li>
  <li><a href="#validation-of-the-grading-rule" id="toc-validation-of-the-grading-rule" class="nav-link" data-scroll-target="#validation-of-the-grading-rule">6.3 Validation of the grading rule</a></li>
  </ul></li>
  <li><a href="#sample-size-and-power" id="toc-sample-size-and-power" class="nav-link" data-scroll-target="#sample-size-and-power">7. Sample size and power</a>
  <ul class="collapse">
  <li><a href="#realized-counts" id="toc-realized-counts" class="nav-link" data-scroll-target="#realized-counts">Realized counts</a></li>
  <li><a href="#the-probe-that-changed-the-design" id="toc-the-probe-that-changed-the-design" class="nav-link" data-scroll-target="#the-probe-that-changed-the-design">The probe that changed the design</a></li>
  <li><a href="#the-baseline-rate-and-a-reasoning-error-the-probe-caught" id="toc-the-baseline-rate-and-a-reasoning-error-the-probe-caught" class="nav-link" data-scroll-target="#the-baseline-rate-and-a-reasoning-error-the-probe-caught">The baseline rate, and a reasoning error the probe caught</a></li>
  <li><a href="#detectable-odds-ratio-at-80-percent-power-alpha-0.05" id="toc-detectable-odds-ratio-at-80-percent-power-alpha-0.05" class="nav-link" data-scroll-target="#detectable-odds-ratio-at-80-percent-power-alpha-0.05">Detectable odds ratio at 80 percent power, alpha 0.05</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis">8. Analysis</a></li>
  <li><a href="#threats-and-what-happened-to-each" id="toc-threats-and-what-happened-to-each" class="nav-link" data-scroll-target="#threats-and-what-happened-to-each">9. Threats, and what happened to each</a></li>
  <li><a href="#the-probes-that-must-run-before-this-is-a-protocol" id="toc-the-probes-that-must-run-before-this-is-a-protocol" class="nav-link" data-scroll-target="#the-probes-that-must-run-before-this-is-a-protocol">10. The probes that must run before this is a protocol</a></li>
  <li><a href="#deviations" id="toc-deviations" class="nav-link" data-scroll-target="#deviations">11. Deviations</a></li>
  <li><a href="#what-this-design-still-cannot-do" id="toc-what-this-design-still-cannot-do" class="nav-link" data-scroll-target="#what-this-design-still-cannot-do">12. What this design still cannot do</a></li>
  <li><a href="#availability" id="toc-availability" class="nav-link" data-scroll-target="#availability">13. Availability</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/choxos/autometaresearch/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Advocacy and practice in meta-research: protocol</h1>
  <div class="quarto-categories">
    <div class="quarto-category">protocol</div>
    <div class="quarto-category">datashare</div>
    <div class="quarto-category">confirmatory</div>
  </div>
  </div>

<div>
  <div class="description">
    Confirmatory protocol for P01 on an independent sample. Feasibility probes computed; two validation gates need human labels; awaiting peer review.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Status: BLOCKED BY REVIEW on 2026-09-19. Do not run this.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Both reviewers returned <strong>unsound</strong>. Three fatal findings and nineteen major, every severe one carrying a verbatim quote. The full review is at <a href="../reviews/P01v2.html">reviews/P01v2</a> and the verdict is <code>blocked</code>, which under the adjudication rule means an evidenced fatal finding stands unrebutted.</p>
<p><strong>The two fatal findings were verified against primary source before publication, and both are correct.</strong></p>
<ol type="1">
<li><p><strong>This is not a confirmatory protocol and calling it one was wrong.</strong> Probe P4 tabulated the primary outcome by arm on the confirmatory sample: 95 of 520 exposed against 132 of 3435 comparison, a crude odds ratio near 5.6. The hypothesis has already been looked at on this data. Running the planned model now would be confirming something already seen. Both reviewers found this independently, and it is the same class of error R01 was reclassified for, made again one document later while explicitly trying to avoid it.</p></li>
<li><p><strong>The outcome instrument has false negatives in both directions.</strong> PMC5808091 and PMC6092896 both carry a data availability statement and the pinned extractor returns nothing for them, because their statement is in <code>&lt;body&gt;</code> and extraction was restricted to <code>&lt;front&gt;</code> and <code>&lt;back&gt;</code>. That restriction was added to fix the contamination artifact documented in R01, and the cost of the fix was never measured. Separately, <code>_text()</code> keeps an <code>ext-link</code>’s visible text and discards its <code>xlink:href</code>, so PMC10202448’s statement reads “on the associated GitHub repository (” with the URL gone, and a real deposit grades declarative.</p></li>
</ol>
<p>The document below is left exactly as reviewed. It is the record of what was submitted, not a corrected version, and a successor protocol will be a new document.</p>
</div>
</div>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What the document claimed when it was submitted
</div>
</div>
<div class="callout-body-container callout-body">
<p>Written against the sibling project’s <code>studies/DESIGN-STANDARD.md</code>, whose governing rule is that <strong>the difference between a design and a protocol is a set of computed numbers</strong>. An earlier version of this page was a design that failed that rule: section 7 assumed a PMC rate and a screening yield and multiplied them into a sample size. Probes P1 to P5 have now been run and section 7 is written from their output, not from assumptions.</p>
<p>Two probes remain and neither can be run by a model. <strong>P6 and P7 need the author’s own labels</strong> on 200 records and 150 statements. Those files exist with empty label columns. Until they come back, screening agreement and grading agreement are unknown and the study does not run.</p>
<p><strong>No outcome has been analyzed under this protocol.</strong> The probes measured the frame and the instruments; they did not test the hypothesis, and no exposure-by-outcome model has been fitted on this sample.</p>
<p><strong>No review has happened.</strong> Review is by two models from different providers, each instructed to refute this document, adjudicated by the fixed rule in <code>build/audit/adjudicate.py</code>. The second reviewer is quota-blocked until 2026-09-20 and the standing rule is two reviewers or none. Sending this to review before the author labels P6 and P7 is deliberate: a reviewer who objects to the validation gates should say so before 350 items are labeled by hand.</p>
<p>Order, which is the user’s explicit instruction: full protocol, then peer review, then conduct the study, then peer review the result.</p>
<p>This supersedes <a href="../proposals/P01-advocacy-and-practice.html">P01</a>, a one-page proposal left unedited as the record of what was actually pre-specified for <a href="../results/R01-advocacy-and-practice.html">R01</a>.</p>
</div>
</div>
<section id="why-this-design-exists" class="level2">
<h2 class="anchored" data-anchor-id="why-this-design-exists">1. Why this design exists</h2>
<p>R01 found that meta-research articles about data sharing point at a repository of their own about four times as often as meta-research articles on other subjects. That result is exploratory and cannot be made confirmatory after the fact, for three reasons stated on its own page: the grading rule was developed by reading the analysis data, three of four sensitivity analyses were post hoc, and no human validation was done.</p>
<p>This specifies a confirmatory test of the same hypothesis, on a sample R01 did not use, with every instrument fixed before any data are retrieved.</p>
</section>
<section id="objective-and-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="objective-and-hypothesis">2. Objective and hypothesis</h2>
<p><strong>Primary objective.</strong> To test whether a meta-research article whose subject is data sharing, code availability or research transparency is more likely than a meta-research article on another aspect of research practice to carry an actionable data availability statement of its own.</p>
<p><strong>Primary hypothesis.</strong> It is, and the association is directional.</p>
<p><strong>Primary null.</strong> The odds ratio for the transparency exposure is 1.</p>
<p><strong>What would falsify the hypothesis.</strong> An adjusted odds ratio whose 95 percent confidence interval includes 1, in a sample powered as in section 7. Section 7 fixes the power in advance so that a null can be read as evidence of absence rather than absence of evidence, which was not true of R01.</p>
<p><strong>Prior expectation, stated so it cannot be revised.</strong> R01 estimated 4.40 (1.80 to 10.75) on a different sample with a rule developed on that sample. Regression to the mean and the removal of rule-development bias both predict a smaller effect here. An estimate between 1.5 and 3 would be consistent with R01; an estimate at or above 4 would be surprising and should itself be treated with suspicion rather than as confirmation.</p>
</section>
<section id="design" class="level2">
<h2 class="anchored" data-anchor-id="design">3. Design</h2>
<p>Cross-sectional study of published articles. The unit of analysis is one article.</p>
</section>
<section id="sample" class="level2">
<h2 class="anchored" data-anchor-id="sample">4. Sample</h2>
<section id="frame" class="level3">
<h3 class="anchored" data-anchor-id="frame">4.1 Frame</h3>
<p>The frame is the qualified tier B search described in <a href="../methods.html">methods</a>, which ANDs a topic block with a study-of-literature qualifier. Measured in PubMed on 2026-09-16:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>block</th>
<th>qualified hits</th>
<th>already in tier A</th>
<th>available to this study</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>datashare</code></td>
<td>754</td>
<td>27</td>
<td><strong>727</strong></td>
</tr>
<tr class="even">
<td><code>report</code></td>
<td>2392</td>
<td>103</td>
<td><strong>2289</strong></td>
</tr>
<tr class="odd">
<td><code>reg</code></td>
<td>4450</td>
<td>88</td>
<td><strong>4362</strong></td>
</tr>
<tr class="even">
<td><code>repro</code></td>
<td>229</td>
<td>14</td>
<td><strong>215</strong></td>
</tr>
</tbody>
</table>
<p><strong>Every record already present in the tier A corpus is excluded</strong>, by PMID, before screening. That exclusion is what makes this sample independent of R01, and it is applied first so that no later decision can reintroduce an overlapping record.</p>
</section>
<section id="eligibility" class="level3">
<h3 class="anchored" data-anchor-id="eligibility">4.2 Eligibility</h3>
<p><strong>Include</strong> an article when all of the following hold:</p>
<ol type="1">
<li>Retrieved by the qualified tier B search for one of the four blocks above.</li>
<li>Not present in the tier A corpus harvested on 2026-09-16.</li>
<li>Screened as meta-research: its object of study is published research, researchers, journals or the research process, rather than patients, organisms, materials or clinical outcomes.</li>
<li>Present in PMC with a <code>&lt;body&gt;</code> element longer than 500 characters, so that a statement could have been extracted had one existed.</li>
</ol>
<p><strong>Exclude</strong> an article when any of the following hold:</p>
<ol type="1">
<li>Its publication type is comment, editorial, letter, news, biography or historical article. R01 estimated an odds ratio of 0.04 for this group; an article with no data of its own belongs to a different population and its absence of a statement is not evidence about sharing behavior. R01 adjusted for this. This protocol excludes it, which is cleaner.</li>
<li>It is a retracted publication or a retraction notice.</li>
<li>It is not in English. R01 applied no language limit; a statement in another language would be graded <code>none</code> by an English-language rule, which is a measurement failure rather than a finding.</li>
</ol>
</section>
<section id="screening" class="level3">
<h3 class="anchored" data-anchor-id="screening">4.3 Screening</h3>
<p>Criterion 3 is the one no boolean query settles, and the reason tier B was never harvested for the map. Screening is on title and abstract, by two models from different providers, each given the same written criterion and blind to the other.</p>
<ul>
<li>Both agree include: included.</li>
<li>Both agree exclude: excluded.</li>
<li>Disagreement: adjudicated by the author. The count of disagreements is reported.</li>
</ul>
<p><strong>Before screening the frame</strong>, 200 records sampled at random across the four blocks are screened by the author to create a reference standard. Agreement is reported as Cohen’s kappa per model. <strong>If neither model reaches kappa 0.75 against the reference standard, screening by model is abandoned</strong> and the study proceeds on a random subsample screened entirely by the author, with the sample size reduced accordingly and the power recomputed and reported.</p>
</section>
</section>
<section id="exposure" class="level2">
<h2 class="anchored" data-anchor-id="exposure">5. Exposure</h2>
<p><strong>Exposed</strong>: retrieved by the qualified <code>datashare</code> block and screened in.</p>
<p><strong>Unexposed</strong>: retrieved by the qualified <code>report</code>, <code>reg</code> or <code>repro</code> blocks, screened in, and not also retrieved by the <code>datashare</code> block.</p>
<p>An article retrieved by <code>datashare</code> and by another block is <strong>exposed</strong>. The exposure is whether transparency is among the article’s subjects, not whether it is the only one.</p>
<p>This is a coarser exposure than a judgment of what an article is primarily about, and that is deliberate: it is reproducible from a query string, and its misclassification is toward the null. The alternative, asking a model what each article is mainly about, adds a second instrument needing its own validation to measure something the query already approximates.</p>
</section>
<section id="outcome" class="level2">
<h2 class="anchored" data-anchor-id="outcome">6. Outcome</h2>
<section id="extraction" class="level3">
<h3 class="anchored" data-anchor-id="extraction">6.1 Extraction</h3>
<p>The data availability statement is taken from the JATS full text by <code>studies/P01-advocacy-and-practice/extract.py</code> <strong>as it stands at commit <code>158164be700a596610a074533e6509ce142a6774</code></strong>, unchanged. A prose pin is not a pin; that hash is the pin, and <code>git show 158164be700a596610a074533e6509ce142a6774:studies/P01-advocacy-and-practice/extract.py</code> is how a reader checks it. That code searches <code>&lt;front&gt;</code> and <code>&lt;back&gt;</code> only, never <code>&lt;body&gt;</code>, in this order: a section or notes block with a <code>sec-type</code> or <code>notes-type</code> naming data availability; a section or notes block whose title matches the data availability pattern; a <code>custom-meta</code> pair whose name matches it.</p>
<p>The restriction to front and back matter is not a detail. Without it, a paper <em>about</em> data availability has its own methods and results read as its disclosure, which is the artifact that contaminated 4 of 43 exposed records in R01 and is documented there.</p>
</section>
<section id="grading" class="level3">
<h3 class="anchored" data-anchor-id="grading">6.2 Grading</h3>
<p>Three ordered levels, graded by the rule in <code>studies/_shared/R/grade.R</code> at that same commit, reproduced here in full so that no later edit can pass unnoticed:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>grade</th>
<th>definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>none</code></td>
<td>no statement in front or back matter</td>
</tr>
<tr class="even">
<td><code>declarative</code></td>
<td>a statement that shares nothing: available on request, contained within the article or its supplementary files, or not applicable</td>
</tr>
<tr class="odd">
<td><code>actionable</code></td>
<td>a named repository, or a DOI or URL that is not the article’s own</td>
</tr>
</tbody>
</table>
<p>Tests apply in this order, and the order is itself pre-specified because changing it changes the result:</p>
<ol type="1">
<li>A named repository present, from the fixed list in <code>REPO</code>: <strong>actionable</strong>. A repository outranks a co-occurring on-request clause, because an article that deposits its code and separately withholds licensed raw data has shared what it could.</li>
<li>An on-request clause present: <strong>declarative</strong>.</li>
<li>A not-applicable clause present: <strong>declarative</strong>.</li>
<li>A DOI or URL present that is not the article’s own DOI: <strong>actionable</strong>.</li>
<li>Otherwise: <strong>declarative</strong>.</li>
</ol>
<p><strong>Primary outcome</strong>: <code>actionable</code> versus not.</p>
<p><strong>Secondary outcome</strong>: the three-level ordinal grade.</p>
</section>
<section id="validation-of-the-grading-rule" class="level3">
<h3 class="anchored" data-anchor-id="validation-of-the-grading-rule">6.3 Validation of the grading rule</h3>
<p><strong>This is a gate, not a report.</strong> 150 statements, stratified by rule grade, are graded by the author, blind to the article’s exposure and to the rule’s grade. Agreement is reported as Cohen’s kappa with a 95 percent confidence interval.</p>
<ul>
<li><strong>Kappa at or above 0.80</strong>: the rule is used as the primary instrument.</li>
<li><strong>Kappa 0.60 to 0.79</strong>: the rule is used, and the primary analysis is repeated on the hand-graded subsample alone as a co-primary, with both reported together regardless of whether they agree.</li>
<li><strong>Kappa below 0.60</strong>: the rule is abandoned. The study proceeds on a hand-graded random sample, with power recomputed and reported.</li>
</ul>
<p>The rule is not modified after seeing the validation. If validation shows it is wrong, the wrongness is reported and the fallback above is taken. This is the commitment R01 could not make because its rule was written while the data were being read.</p>
</section>
</section>
<section id="sample-size-and-power" class="level2">
<h2 class="anchored" data-anchor-id="sample-size-and-power">7. Sample size and power</h2>
<p><strong>Computed by probes P1 to P5 on 2026-09-16. Every number in this section is emitted by <code>studies/P01v2-confirmatory/out/probes.json</code> and is not retyped from anywhere.</strong></p>
<section id="realized-counts" class="level3">
<h3 class="anchored" data-anchor-id="realized-counts">Realized counts</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>step</th>
<th>exposed</th>
<th>comparison</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>frame, after removing 205 tier A overlaps from 7617 records</td>
<td>704</td>
<td>6526</td>
</tr>
<tr class="even">
<td>carrying a PMCID</td>
<td>547</td>
<td>3770</td>
</tr>
<tr class="odd">
<td>with PMC full text, the analysis set before screening</td>
<td><strong>520</strong></td>
<td><strong>3435</strong></td>
</tr>
</tbody>
</table>
<p>The exposed arm is 520, not the 260 the discarded assumption produced. The design is better powered than it was written to be.</p>
</section>
<section id="the-probe-that-changed-the-design" class="level3">
<h3 class="anchored" data-anchor-id="the-probe-that-changed-the-design">The probe that changed the design</h3>
<p><strong>PMC coverage differs sharply between arms: 77.7 percent of exposed records against 57.8 percent of comparison records.</strong> The discarded assumption was a flat 60 percent for both, close to tier A’s 59.5 percent, and it would have concealed a 20 point differential.</p>
<p>This is not a nuisance; it is adjacent to the hypothesis. Papers about data sharing are much likelier to be openly available, which is itself a transparency behavior. The consequence for this study is that the two arms are selected differently into the analysis set, and section 9 carries it as a disclosed threat that the design cannot remove.</p>
</section>
<section id="the-baseline-rate-and-a-reasoning-error-the-probe-caught" class="level3">
<h3 class="anchored" data-anchor-id="the-baseline-rate-and-a-reasoning-error-the-probe-caught">The baseline rate, and a reasoning error the probe caught</h3>
<p>On the unscreened frame the comparison arm is 3.8 percent actionable and the exposed arm 18.3 percent.</p>
<p>A comment in the probe code asserted that the unscreened comparison rate would be an <strong>upper</strong> bound on the screened one, because primary studies carry journal-mandated statements. That was backwards. R01’s rate among screened meta-research was 20.5 percent against 3.8 percent here, so screening removes records that deposit <em>less</em> often and <strong>raises</strong> the comparison rate. The unscreened figure is a lower bound.</p>
<p>The power calculation therefore runs across a range of plausible screened baselines rather than at any single assumed one.</p>
</section>
<section id="detectable-odds-ratio-at-80-percent-power-alpha-0.05" class="level3">
<h3 class="anchored" data-anchor-id="detectable-odds-ratio-at-80-percent-power-alpha-0.05">Detectable odds ratio at 80 percent power, alpha 0.05</h3>
<p>Rows are the screened comparison-arm actionable rate; columns are the proportion of records surviving screening, which shrinks both arms.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>baseline rate</th>
<th>yield 0.5</th>
<th>yield 0.7</th>
<th>yield 1.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.038</td>
<td>2.18</td>
<td>1.97</td>
<td>1.79</td>
</tr>
<tr class="even">
<td>0.1</td>
<td>1.72</td>
<td>1.6</td>
<td>1.49</td>
</tr>
<tr class="odd">
<td>0.15</td>
<td>1.6</td>
<td>1.5</td>
<td>1.41</td>
</tr>
<tr class="even">
<td>0.205</td>
<td>1.53</td>
<td>1.44</td>
<td>1.36</td>
</tr>
<tr class="odd">
<td>0.25</td>
<td>1.5</td>
<td>1.41</td>
<td>1.34</td>
</tr>
</tbody>
</table>
<p><strong>Across the whole grid the detectable odds ratio is at most 2.18.</strong> R01’s point estimate was 4.40 and section 2 states that anything between 1.5 and 3 would be consistent with it. The design detects effects across that entire band, which is the property R01 lacked: its floor was roughly 3.7, so it could only ever have seen an effect as large as the one it reported.</p>
<p>A null result here rules something out.</p>
</section>
</section>
<section id="analysis" class="level2">
<h2 class="anchored" data-anchor-id="analysis">8. Analysis</h2>
<p>In R. All models fitted with <code>lme4</code> or <code>ordinal</code>.</p>
<p><strong>Primary.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glmer</span>(actionable <span class="sc">~</span> exposed <span class="sc">+</span> year_c <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> journal),</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">family =</span> binomial, <span class="at">data =</span> d,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">control =</span> <span class="fu">glmerControl</span>(<span class="at">optimizer =</span> <span class="st">"bobyqa"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Article type does not enter the model because section 4.2 excludes the type that mattered.</p>
<p><strong>Secondary, preregistered.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clmm</span>(grade <span class="sc">~</span> exposed <span class="sc">+</span> year_c <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> journal), <span class="at">data =</span> d)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Sensitivity analyses, all preregistered here, all reported whatever they show.</strong></p>
<ol type="1">
<li>Supplementary material graded actionable rather than declarative.</li>
<li>Publisher-typed extraction routes only, excluding title-matched routes.</li>
<li>Journal as a fixed effect, restricted to journals contributing at least 10 articles in each arm, as a within-journal estimate that does not rely on the random-effect assumption.</li>
<li>Excluding any article authored by the author of this project.</li>
<li>Excluding the <code>repro</code> block from the comparison arm, since reproducibility and data sharing are adjacent subjects and their separation is the weakest part of the exposure definition.</li>
<li>Restricted to fully open-access journals, added after probe P2 found that PMC coverage differs by 20 points between arms. Within a fully open-access journal every article is in PMC, so the differential selection that P2 exposed cannot operate. This is a post-probe addition and is labeled as one.</li>
</ol>
<p><strong>Missing data.</strong> Year is present for every PubMed record. Journal is present for every record. No imputation is performed and no analysis drops a record for missingness; records are excluded only by section 4.2.</p>
<p><strong>Multiplicity.</strong> There is one primary comparison. The secondary and the five sensitivity analyses are not corrected for multiplicity and are not used to claim significance; they exist to show whether the primary estimate is fragile.</p>
</section>
<section id="threats-and-what-happened-to-each" class="level2">
<h2 class="anchored" data-anchor-id="threats-and-what-happened-to-each">9. Threats, and what happened to each</h2>
<p>A threat that is disclosed rather than removed is acceptable. A threat that is silently absent is not. Every design choice made after seeing a number is listed, because R01 was exploratory and anything carried forward from it makes a later choice suspect unless it is named.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>threat</th>
<th>what was done</th>
<th>removed or disclosed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Grading rule was developed on R01’s data</td>
<td>Rule frozen at the pinned commit and applied unchanged to a sample it has never seen</td>
<td>Removed</td>
</tr>
<tr class="even">
<td>Extractor read papers’ own results as their disclosure</td>
<td>Restricted to <code>&lt;front&gt;</code> and <code>&lt;back&gt;</code>; the artifact and its cost are documented in R01</td>
<td>Removed</td>
</tr>
<tr class="odd">
<td>Repository regex matched inside longer words</td>
<td>Word boundaries added before pinning</td>
<td>Removed</td>
</tr>
<tr class="even">
<td>Exposure is a query, not a judgment of subject</td>
<td>Kept deliberately, for reproducibility; misclassification is toward the null</td>
<td>Disclosed</td>
</tr>
<tr class="odd">
<td>Comparison arm blocks chosen after seeing R01</td>
<td><code>report</code>, <code>reg</code> and <code>repro</code> were picked because they are the other large qualified blocks, not because of any result; sensitivity 5 drops <code>repro</code> as the most arguable</td>
<td>Disclosed</td>
</tr>
<tr class="even">
<td>PMC coverage is not random</td>
<td>Not fixable in this design</td>
<td>Disclosed</td>
</tr>
<tr class="odd">
<td><strong>PMC coverage differs by arm</strong>, 77.7 percent exposed against 57.8 percent comparison</td>
<td>Found by probe P2, not anticipated when the design was written. Arms are differentially selected into the analysis set and the direction favors the hypothesis. Reported as a primary limitation; a sensitivity restricted to journals that are fully open access is added as analysis 6</td>
<td>Disclosed, not removed</td>
</tr>
<tr class="even">
<td>Screening depends on a model</td>
<td>Gated on kappa against a human reference standard, with a stated fallback</td>
<td>Disclosed</td>
</tr>
<tr class="odd">
<td>Comparison-arm rate of 0.205 comes from R01</td>
<td>Used for planning only; the realized rate is computed in probe P4 and is what the power calculation uses</td>
<td>Disclosed</td>
</tr>
</tbody>
</table>
</section>
<section id="the-probes-that-must-run-before-this-is-a-protocol" class="level2">
<h2 class="anchored" data-anchor-id="the-probes-that-must-run-before-this-is-a-protocol">10. The probes that must run before this is a protocol</h2>
<p>Each probe names the number it produces, the section that number goes into, what result would change the design, and its cost. Nothing here is an argument; each one is a count.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>probe</th>
<th>computes</th>
<th>goes to</th>
<th>what would change the design</th>
<th>cost</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>P1</strong> done</td>
<td>Records retrieved by the four qualified blocks, after removing every tier A PMID</td>
<td>4.1</td>
<td>An available count far below 727 for <code>datashare</code> makes the confirmatory arm underpowered and the design moves to a prospective re-harvest instead</td>
<td>~10 min, cached</td>
</tr>
<tr class="even">
<td><strong>P2</strong> done</td>
<td>Proportion of P1 records carrying a PMCID</td>
<td>4.2, 7</td>
<td>Below about 40 percent and the realized exposed count falls under 150, at which point this is no better powered than R01 and is not worth running</td>
<td>minutes</td>
</tr>
<tr class="odd">
<td><strong>P3</strong> done</td>
<td>Proportion of P2 records with a <code>&lt;body&gt;</code> over 500 characters, and the extraction route distribution on this frame</td>
<td>4.2, 6.1</td>
<td>A route distribution unlike tier A’s means publishers differ between frames and journal adjustment is carrying more weight than assumed</td>
<td>~20 min, cached</td>
</tr>
<tr class="even">
<td><strong>P4</strong> done</td>
<td>Grade distribution on the comparison arm under the pinned rule</td>
<td>7</td>
<td>An actionable rate far from R01’s 0.205 changes every power figure</td>
<td>seconds, after P3</td>
</tr>
<tr class="odd">
<td><strong>P5</strong> done</td>
<td>Detectable odds ratio at 80 percent power from the realized counts in P1 to P4</td>
<td>7</td>
<td>A detectable effect above about 2.5 means the study cannot distinguish R01’s estimate from a much smaller one and the frame must be widened</td>
<td>seconds</td>
</tr>
<tr class="even">
<td><strong>P6</strong> outstanding, needs the author</td>
<td>Screening agreement: Cohen’s kappa of each model against a 200-record human reference standard</td>
<td>4.3</td>
<td>Below 0.75 for every model triggers the hand-screening fallback and a smaller sample</td>
<td>200 records to label</td>
</tr>
<tr class="odd">
<td><strong>P7</strong> outstanding, needs the author</td>
<td>Grading agreement: Cohen’s kappa of the pinned rule against 150 human-graded statements</td>
<td>6.3</td>
<td>Below 0.60 abandons the rule, per 6.3</td>
<td>150 statements to label</td>
</tr>
</tbody>
</table>
<p><strong>P6 and P7 need a person, and that person is the author, not a model.</strong> A model grading a sample to validate a rule another model wrote is not a reference standard, and R01 already shows what that is worth: the 40 statements graded by the model that wrote the rule found a real defect and still left the rule’s agreement with a human unknown. The two CSVs are produced with empty label columns and handed over.</p>
<p>P6 may use a single model while the second reviewer is quota-blocked. Measuring an instrument is not reviewing a study, so the two-reviewer rule does not apply to it; it applies to sections under review, and it is not waived for those.</p>
</section>
<section id="deviations" class="level2">
<h2 class="anchored" data-anchor-id="deviations">11. Deviations</h2>
<p>Any departure from this protocol is recorded in a <code>DEVIATIONS</code> section appended to the result page, stating what changed, when, why, and the estimate before and after where that can be computed. A deviation is not a failure; concealing one is.</p>
</section>
<section id="what-this-design-still-cannot-do" class="level2">
<h2 class="anchored" data-anchor-id="what-this-design-still-cannot-do">12. What this design still cannot do</h2>
<ul>
<li><strong>It is not causal.</strong> Researchers who study transparency and researchers who practice it may be the same people, and the design cannot separate selection from influence.</li>
<li><strong>PMC coverage is not random.</strong> Open-access availability correlates with transparency practice, so both arms lean transparent. The direction of bias on a <em>comparison</em> between arms is not obvious and is not claimed to be toward the null.</li>
<li><strong>The qualified frame is lossy.</strong> The study-of-literature qualifier cut the raw <code>datashare</code> block from 15418 to 754, and a meta-research paper describing its sample as “we examined 300 trials” carries none of the qualifier phrases and is absent from the frame. The sample is a high-precision slice of the field, not the field.</li>
<li><strong>It tests association in one direction only.</strong> A finding that transparency-topic papers share more does not tell us whether writing about transparency changes behavior or whether people who already share choose to write about it.</li>
</ul>
</section>
<section id="availability" class="level2">
<h2 class="anchored" data-anchor-id="availability">13. Availability</h2>
<p>Protocol, code, extracted data and outputs are in the repository at commit <code>158164be700a596610a074533e6509ce142a6774</code>. The analysis code that will run is already written and public; it is the code that produced R01, and section 6 pins it.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/choxos\.github\.io\/autometaresearch\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Ahmad Sofi-Mahmudi</p>
</div>   
    <div class="nav-footer-center">
<p>Every number is derived by a script. See <a href="../methods.html">How this was done</a>.</p>
<div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/choxos/autometaresearch/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/choxos/autometaresearch">Source</a></p>
</div>
  </div>
</footer>




</body></html>